Controllers/FournisseurController.cs
using iStock.Data;
using iStock.Models;
using Microsoft.AspNetCore.Mvc;

namespace iStock.Controllers;

    public class FournisseurController : Controller
    {
    public readonly ApplicationDbContext _db;

    public FournisseurController(ApplicationDbContext db)
    {
        _db = db;
    }
    public IActionResult Index()   
        {
        IEnumerable<Fournisseur> OBJfournisseurs = _db.Fournisseurs;
        return View(OBJfournisseurs);
        }




    // GET - CREATE
    public IActionResult CreateF()
    {
        return View();
    }

	// POST - CREATE
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult CreateF(Fournisseur obj)
	{
		if (ModelState.IsValid)
		{

			_db.Fournisseurs.Add(obj);
			_db.SaveChanges();
			TempData["success"] = "The Fournisseur has been added successfully";
			return RedirectToAction("Index");

		}
		return View(obj);

	}
	// GET - EDIT
	public IActionResult EditF(int? Id)
	
	{
		if (Id == null || Id == 0)
		{
			return NotFound();
		}
		var obj = _db.Fournisseurs.Find(Id);
		
		if(obj==null)
		{
			return NotFound();
		}

		return View(obj);

	}

	// POST - EDIT
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult EditF(Fournisseur obj)
	{
		if (ModelState.IsValid)
		{

			_db.Fournisseurs.Update(obj);
			_db.SaveChanges();
			TempData["success"] = "The Fournisseur has been edited successfully";
			return RedirectToAction("Index");

		}
		return View(obj);

	}








	// GET - DELETE
	public IActionResult DeleteF(int? Id)

	{
		if (Id == null || Id == 0)
		{
			return NotFound();
		}
		var obj = _db.Fournisseurs.Find(Id);

		if (obj == null)
		{
			return NotFound();
		}

		return View(obj);

	}

	// POST - delete
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult DeleteFP(int? Id)
	{
		var obj = _db.Fournisseurs.Find(Id);
		if (obj ==null )
		{
			return NotFound();
		}


		_db.Fournisseurs.Remove(obj);
			_db.SaveChanges();
		TempData["success"] = "The Fournisseur has been deleted successfully";
		return RedirectToAction("Index");

	

	}






}







Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;


namespace iStock.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {

            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/ProduitController.cs
using iStock.Data;
using iStock.Models;
using Microsoft.AspNetCore.Mvc;

namespace iStock.Controllers;

public class ProduitController : Controller           
{
	public readonly ApplicationDbContext _db;

	public ProduitController(ApplicationDbContext db)
	{
		_db = db;
	}
	public IActionResult IndexP()
	{
		IEnumerable<Produit> OBJProduits = _db.Produits;
		return View(OBJProduits);
	}




	// GET - CREATE
	public IActionResult CreateP()
	{
		return View();
	}

	// POST - CREATE
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult CreateP(Produit obj)
	{
		if (ModelState.IsValid)
		{

			_db.Produits.Add(obj);
			_db.SaveChanges();
			TempData["success"] = "The Produit has been added successfully";
			return RedirectToAction("IndexP");

		}
		return View(obj);

	}
	// GET - EDIT
	public IActionResult EditP(int? Id)    

	{
		if (Id == null || Id == 0)
		{
			return NotFound();
		}
		var obj = _db.Produits.Find(Id);

		if (obj == null)
		{
			return NotFound();
		}

		return View(obj);

	}

	// POST - EDIT
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult EditP(Produit obj)
	{
		if (ModelState.IsValid)
		{

			_db.Produits.Update(obj);
			_db.SaveChanges();
			TempData["success"] = "The Produit has been edited successfully";
			return RedirectToAction("IndexP");

		}
		return View(obj);

	}



	


	

	// GET - DELETE
	public IActionResult DeleteP(int? Id)

	{
		if (Id == null || Id == 0)
		{
			return NotFound();
		}
		var obj = _db.Produits.Find(Id);

		if (obj == null)
		{
			return NotFound();
		}

		return View(obj);

	}

	// POST - delete
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult DeletePP(int? Id)
	{
		var obj = _db.Produits.Find(Id);
		if (obj == null)
		{
			return NotFound();
		}


		_db.Produits.Remove(obj);
		_db.SaveChanges();
		TempData["success"] = "The Produit has been deleted successfully";
		return RedirectToAction("IndexP");

		

	}






}



Controllers/WarehouseController.cs
using iStock.Data;
using iStock.Models;
using Microsoft.AspNetCore.Mvc;

namespace iStock.Controllers;

public class WarehouseController : Controller
{
    public readonly ApplicationDbContext _db;

    public WarehouseController(ApplicationDbContext db)
    {
        _db = db;
    }
    public IActionResult IndexW()
    {
        IEnumerable<Warehouse> OBJWarehouses = _db.Warehouses;
        return View(OBJWarehouses);
    }







	// GET - CREATE
	public IActionResult CreateW()
	{
		return View();
	}

	// POST - CREATE
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult CreateW(Warehouse obj)
	{
		if (ModelState.IsValid)
		{

			_db.Warehouses.Add(obj);
			_db.SaveChanges();
			TempData["success"] = "The Warehouse has been added successfully";
			return RedirectToAction("IndexW");

		}
		return View(obj);

	}
	// GET - EDIT
	public IActionResult EditW(int? Id)

	{
		if (Id == null || Id == 0)
		{
			return NotFound();
		}
		var obj = _db.Warehouses.Find(Id);

		if (obj == null)
		{
			return NotFound();
		}

		return View(obj);

	}

	// POST - EDIT
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult EditW(Warehouse obj)
	{
		if (ModelState.IsValid)
		{

			_db.Warehouses.Update(obj);
			_db.SaveChanges();
			TempData["success"] = "The Warehouse has been edited successfully";
			return RedirectToAction("IndexW");

		}
		return View(obj);

	}








	// GET - DELETE
	public IActionResult DeleteW(int? Id)

	{
		if (Id == null || Id == 0)
		{
			return NotFound();
		}
		var obj = _db.Warehouses.Find(Id);

		if (obj == null)
		{
			return NotFound();
		}

		return View(obj);

	}

	// POST - delete
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult DeleteWP(int? Id)
	{
		var obj = _db.Warehouses.Find(Id);
		if (obj == null)
		{
			return NotFound();
		}


		_db.Warehouses.Remove(obj);
		_db.SaveChanges();
		TempData["success"] = "The Warehouse has been deleted successfully";
		return RedirectToAction("IndexW");



	}


































}


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iStock</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">iStock</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Fournisseur" asp-action="Index">Fournisseur</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Warehouse" asp-action="IndexW">Warehouse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Produit" asp-action="IndexP">Produit</a>
                        </li>








                        


                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Logout" asp-action="Index">Logout</a>
                        </li>
                    </ul>                                            
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
        
    


    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title> @ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>



    
    
    

</body>





<a href="c:\users\houssammrd\source\repos\istockmanag\istock\views\shared\_layoutpage.cshtml"></a>

</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.success('@TempData["success"]');
        </script>
}
@if (TempData["error"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.error('@TempData["error"]');
        </script>
}